services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: phishing-backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - phishing-net
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - SECRET_KEY=7230

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Assumes your Dockerfile is named correctly
    container_name: phishing-frontend
    ports:
      - "3000:3000"
    networks:
      - phishing-net

  nginx:
    image: nginx:latest
    container_name: phishing-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - phishing-net

networks:
  phishing-net:
